127.0.0.1 - - [19/Jul/2025 10:56:34] "GET /dashboard.html HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:56:37] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:56:37] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 10:56:37] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 10:56:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:56:47] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:56:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:56:57] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:56:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:07] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:07] "GET /dashboard.html HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:10] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:10] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 10:57:10] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 10:57:10] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:21] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:29] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:29] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 10:57:29] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 10:57:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:32] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:39] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:39] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:42] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:49] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:49] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:52] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:59] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:57:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:58:02] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:58:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:58:09] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:58:09] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:58:12] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:58:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:01] "GET /dashboard.html HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:04] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:04] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 10:59:04] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 10:59:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:14] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:24] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:34] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:44] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:54] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 10:59:54] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:00:04] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:00:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:00:14] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:00:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:00:24] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:00:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:00:34] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:00:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:01:26] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:01:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:01:54] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:01:54] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:01:54] "GET /dashboard.html HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:01:57] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:01:57] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 11:01:57] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 11:01:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:07] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:17] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:27] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:37] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:47] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:57] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:02:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:07] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:17] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:23] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:23] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 11:03:23] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 11:03:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:33] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:44] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:53] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:03:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:03] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:13] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:23] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:33] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:43] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:54] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:04:54] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:03] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:13] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:13] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 61541)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/Users/admin/HOT/Heroes-of-Time/dashboard-server.py", line 82, in do_GET
    self.send_error(403, "Accès refusé - Fichier non autorisé")
  File "/Users/admin/HOT/Heroes-of-Time/dashboard-server.py", line 94, in send_dashboard
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [19/Jul/2025 11:05:25] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:36] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:36] "GET /dashboard.html HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:36] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 61586)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/Users/admin/HOT/Heroes-of-Time/dashboard-server.py", line 82, in do_GET
    self.send_error(403, "Accès refusé - Fichier non autorisé")
  File "/Users/admin/HOT/Heroes-of-Time/dashboard-server.py", line 94, in send_dashboard
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [19/Jul/2025 11:05:41] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:41] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 11:05:41] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 11:05:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:46] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:46] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:55] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:05:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:06:05] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:06:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:06:28] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:06:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:09] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:09] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 11:07:09] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 11:07:09] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:19] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:19] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:28] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:38] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:48] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:58] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:07:58] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:08] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:08] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 62022)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/Users/admin/HOT/Heroes-of-Time/dashboard-server.py", line 82, in do_GET
    self.send_error(403, "Accès refusé - Fichier non autorisé")
  File "/Users/admin/HOT/Heroes-of-Time/dashboard-server.py", line 94, in send_dashboard
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [19/Jul/2025 11:08:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:15] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:15] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 11:08:15] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 11:08:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:25] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:35] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:45] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:55] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:08:55] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 62181)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/Users/admin/HOT/Heroes-of-Time/dashboard-server.py", line 82, in do_GET
    self.send_error(403, "Accès refusé - Fichier non autorisé")
  File "/Users/admin/HOT/Heroes-of-Time/dashboard-server.py", line 94, in send_dashboard
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [19/Jul/2025 11:09:05] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:15] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:25] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:35] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:44] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:44] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 11:09:44] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 11:09:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:54] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:09:54] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:05] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:05] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 62369)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/Users/admin/HOT/Heroes-of-Time/dashboard-server.py", line 82, in do_GET
    self.send_error(403, "Accès refusé - Fichier non autorisé")
  File "/Users/admin/HOT/Heroes-of-Time/dashboard-server.py", line 94, in send_dashboard
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [19/Jul/2025 11:10:14] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:24] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:27] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:27] code 403, message Accès refusé - Fichier non autorisé
127.0.0.1 - - [19/Jul/2025 11:10:27] "GET /favicon.ico HTTP/1.1" 403 -
127.0.0.1 - - [19/Jul/2025 11:10:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:37] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:47] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:57] "GET /api/global-status HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2025 11:10:57] "GET / HTTP/1.1" 200 -
